tasks:
  - before: |
      npm i -g @nrwl/cli commitizen
    init: npm install
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - nrwl.angular-console
    - jpoissonnier.vscode-styled-components
